package com.qepms.infra.dto.armg;
// default package
// Generated Mar 13, 2014 3:13:19 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Project generated by hbm2java
 */
public class ProjectDTO implements java.io.Serializable {

	private Integer projectId;
	private String clientName;
	private ResumeDTO resume;
	private String projectName;
	private String projectDesc;
	private String role;
	private String responsibility;
	private String environment;
	private String startDate;
	private String endDate;
	private Date createdDate;
	private Date updatedDate;
	private String duration;

	public ProjectDTO(Integer projectId, String clientName, ResumeDTO resume,
			String projectName, String projectDesc, String role,
			String responsibility, String environment, String startDate,
			String endDate, Date createdDate, Date updatedDate, String duration) {
		super();
		this.projectId = projectId;
		this.clientName = clientName;
		this.resume = resume;
		this.projectName = projectName;
		this.projectDesc = projectDesc;
		this.role = role;
		this.responsibility = responsibility;
		this.environment = environment;
		this.startDate = startDate;
		this.endDate = endDate;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.duration = duration;
	}




	public ProjectDTO() {
	}

	
	

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public ResumeDTO getResume() {
		return this.resume;
	}

	public void setResume(ResumeDTO resume) {
		this.resume = resume;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getResponsibility() {
		return this.responsibility;
	}

	public void setResponsibility(String responsibility) {
		this.responsibility = responsibility;
	}

	public String getEnvironment() {
		return this.environment;
	}

	public void setEnvironment(String environment) {
		this.environment = environment;
	}

	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getClientName() {
		return clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}
	public String getDuration() {
		return duration;
	}
	public void setDuration(String duration) {
		this.duration = duration;
	}

}
