package com.qepms.infra.dto.armg;
// default package
// Generated Mar 13, 2014 3:13:19 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Resume generated by hbm2java
 */
public class ResumeDTO implements java.io.Serializable {

	private Integer resumeid;
	private EmployeeMasterDTO employeeMaster;
	
	private String totYear;
	private String totMon;
	private String totalExperience;
	
	private String relYear;
	private String relMon;
	private String relevantExperience;
	
	private List<String> proSummeryList = null;
	
	private String domain;
	private String certification;
	private String professionalSummary;
	private String employeeSumbissionStatus;
	private String managerApprovalStatus;
	private Date createdDate;
	private Date updatedDate;
	private Date approvedDate;
	private Date rejectedDate;
	public Date getRejectedDate() {
		return rejectedDate;
	}

	public void setRejectedDate(Date rejectedDate) {
		this.rejectedDate = rejectedDate;
	}

	public Date getApprovedDate() {
		return approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	private String comments;
	private List<ProjectDTO> projects = new ArrayList<ProjectDTO>();
	private List<EducationDTO> educations = new ArrayList<EducationDTO>();
	private List<SkillDTO> skills = new ArrayList<SkillDTO>();
	
	
	/*
	 * custom date
	 */
	private String customCreatedDate;
	private String customUpdatedDate;
	
	/*
	 * To know if its drafted or submitted
	 */
	private String submissionStatus;
	

	public ResumeDTO() {
	}

	public ResumeDTO(Date createdDate, Date updatedDate) {
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	


	public ResumeDTO(Integer resumeid, EmployeeMasterDTO employeeMaster,String totYear,String totMon,
			String totalExperience, String relYear,String relMon,String relevantExperience, String domain,String certification,
			String professionalSummary, String employeeSumbissionStatus,
			String managerApprovalStatus, Date createdDate, Date updatedDate,
			String comments, List<ProjectDTO> projects,
			List<EducationDTO> educations, List<SkillDTO> skills,
			String submissionStatus,Date approvedDate) {
		super();
		this.resumeid = resumeid;
		this.employeeMaster = employeeMaster;
		this.setTotalExperience(totalExperience);
		this.setRelevantExperience(relevantExperience);
		this.domain= domain;
		this.certification= certification;
		this.professionalSummary = professionalSummary;
		this.employeeSumbissionStatus = employeeSumbissionStatus;
		this.managerApprovalStatus = managerApprovalStatus;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.comments = comments;
		this.projects = projects;
		this.educations = educations;
		this.skills = skills;
		this.submissionStatus = submissionStatus;
		this.approvedDate = approvedDate;
	}

	public Integer getResumeid() {
		return this.resumeid;
	}

	public void setResumeid(Integer resumeid) {
		this.resumeid = resumeid;
	}

	public EmployeeMasterDTO getEmployeeMaster() {
		return this.employeeMaster;
	}

	public void setEmployeeMaster(EmployeeMasterDTO employeeMaster) {
		this.employeeMaster = employeeMaster;
	}

	public String getDomain() {
		return domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getCertification() {
		return certification;
	}

	public void setCertification(String certification) {
		this.certification = certification;
	}

	public String getProfessionalSummary() {
		return this.professionalSummary;
	}

	public void setProfessionalSummary(String professionalSummary) {
		this.professionalSummary = professionalSummary;
	}

	public String getEmployeeSumbissionStatus() {
		return this.employeeSumbissionStatus;
	}

	public void setEmployeeSumbissionStatus(String employeeSumbissionStatus) {
		this.employeeSumbissionStatus = employeeSumbissionStatus;
	}

	public String getManagerApprovalStatus() {
		return this.managerApprovalStatus;
	}

	public void setManagerApprovalStatus(String managerApprovalStatus) {
		this.managerApprovalStatus = managerApprovalStatus;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public List<ProjectDTO> getProjects() {
		return projects;
	}

	public void setProjects(List<ProjectDTO> projects) {
		this.projects = projects;
	}

	public List<EducationDTO> getEducations() {
		return educations;
	}

	public void setEducations(List<EducationDTO> educations) {
		this.educations = educations;
	}

	public List<SkillDTO> getSkills() {
		return skills;
	}

	public void setSkills(List<SkillDTO> skills) {
		this.skills = skills;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getSubmissionStatus() {
		return submissionStatus;
	}

	public void setSubmissionStatus(String submissionStatus) {
		this.submissionStatus = submissionStatus;
	}

	public String getTotYear() {
		return totYear;
	}

	public void setTotYear(String totYear) {
		
		this.totYear = totYear;
	}

	public String getTotMon() {
		return totMon;
	}

	public void setTotMon(String totMon) {
		
		this.totMon = totMon;
	}

	public String getTotalExperience() {
		return totalExperience;
	}

	public void setTotalExperience(String totalExperience) {
		this.totalExperience = totalExperience;
	}

	public String getRelYear() {
		return relYear;
	}

	public void setRelYear(String relYear) {
		this.relYear = relYear;
	}

	public String getRelMon() {
		return relMon;
	}

	public void setRelMon(String relMon) {
		this.relMon = relMon;
	}

	public String getRelevantExperience() {
		return relevantExperience;
	}

	public void setRelevantExperience(String relevantExperience) {
		this.relevantExperience=relevantExperience;
	}

	public String getCustomCreatedDate() {
		return customCreatedDate;
	}

	public void setCustomCreatedDate(String customCreatedDate) {
		this.customCreatedDate = customCreatedDate;
	}

	public String getCustomUpdatedDate() {
		return customUpdatedDate;
	}

	public void setCustomUpdatedDate(String customUpdatedDate) {
		this.customUpdatedDate = customUpdatedDate;
	}

	public List<String> getProSummeryList() {
		return proSummeryList;
	}

	public void setProSummeryList(List<String> proSummeryList) {
		this.proSummeryList = proSummeryList;
	}

}
