package com.qepms.data.employee;
// default package
// Generated Mar 13, 2014 3:13:19 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EmployeeMaster generated by hbm2java
 */
public class EmployeeMaster implements java.io.Serializable {

	private Integer empId;
	private String name;
	private String title;
	private String currentProject;
	private String reportingManager;
	private String employeeMail;
	private String managerMail;
	private Date createdDate;
	private Date updatedDate;
	private String group;
	private Set resumes = new HashSet(0);

	public EmployeeMaster() {
	}

	public EmployeeMaster(Date createdDate, Date updatedDate) {
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	
	public EmployeeMaster(Integer empId, String name, String title,
			String currentProject, String reportingManager,
			String employeeMail, String managerMail, Date createdDate,
			Date updatedDate, String group, Set resumes) {
		super();
		this.empId = empId;
		this.name = name;
		this.title = title;
		this.currentProject = currentProject;
		this.reportingManager = reportingManager;
		this.employeeMail = employeeMail;
		this.managerMail = managerMail;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.group = group;
		this.resumes = resumes;
	}

	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCurrentProject() {
		return this.currentProject;
	}

	public void setCurrentProject(String currentProject) {
		this.currentProject = currentProject;
	}

	public String getReportingManager() {
		return this.reportingManager;
	}

	public void setReportingManager(String reportingManager) {
		this.reportingManager = reportingManager;
	}

	public String getEmployeeMail() {
		return this.employeeMail;
	}

	public void setEmployeeMail(String employeeMail) {
		this.employeeMail = employeeMail;
	}

	public String getManagerMail() {
		return this.managerMail;
	}

	public void setManagerMail(String managerMail) {
		this.managerMail = managerMail;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Set getResumes() {
		return this.resumes;
	}

	public void setResumes(Set resumes) {
		this.resumes = resumes;
	}

	public String getGroup() {
		return group;
	}

	public void setGroup(String group) {
		this.group = group;
	}

}
