package com.qepms.data.employee;
// default package
// Generated Mar 13, 2014 3:13:19 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Resume generated by hbm2java
 */
public class Resume implements java.io.Serializable {

	@Override
	public String toString() {
		return "Resume [resumeid=" + resumeid + ", employeeMaster="
				+ employeeMaster + ", totalExperience=" + totalExperience
				+ ", relevantExperience=" + relevantExperience+", relYear="+relYear+", relMon="+relMon
				+ ", domain=" + domain + ", totYear=" + totYear+",totMon="+totMon
				+ ", certification=" + certification
				+ ", professionalSummary=" + professionalSummary
				+ ", employeeSumbissionStatus=" + employeeSumbissionStatus
				+ ", managerApprovalStatus=" + managerApprovalStatus
				+ ", createdDate=" + createdDate + ", updatedDate="
				+ updatedDate + ", comments=" + comments + ", projects="
				+ projects + ", educations=" + educations + ", skills="
				+ skills + ", approvedDate="+approvedDate+", rejectedDate="+rejectedDate+"]";
	}

	private Integer resumeid;
	private EmployeeMaster employeeMaster;
	private String totYear;
	private String totMon;
	private String totalExperience;
	private String relYear;
	private String relMon;
	private String relevantExperience;
	private String domain;
	private String certification;
	private String professionalSummary;
	private String employeeSumbissionStatus;
	private String managerApprovalStatus;
	private Date createdDate;
	private Date updatedDate;
	private String comments;
	public Date getApprovedDate() {
		return approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	private Date approvedDate;
	private Date rejectedDate;
	private Set projects = new HashSet(0);
	private Set educations = new HashSet(0);
		private Set skills=new HashSet(0);

	public Resume() {
	}

	public Date getRejectedDate() {
		return rejectedDate;
	}

	public void setRejectedDate(Date rejectedDate) {
		this.rejectedDate = rejectedDate;
	}

	public Resume(Date createdDate, Date updatedDate) {
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	

/*	public Resume(Date createdDate, Date updatedDate,Date approvedDate ) {
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.approvedDate = approvedDate;
	}*/

	public Resume(Integer resumeid, EmployeeMaster employeeMaster,
			String totalExperience, String relevantExperience,String domain, String certification,
			String professionalSummary, String employeeSumbissionStatus,
			String managerApprovalStatus, Date createdDate, Date updatedDate,
			Set projects, Set educations, Set skills,Date approvedDate,Date rejectedDate) {
		super();
		this.resumeid = resumeid;
		this.employeeMaster = employeeMaster;
		this.setTotalExperience(totalExperience);
		this.setRelevantExperience(relevantExperience);
		this.domain=domain;
		this.certification=certification;
		this.professionalSummary = professionalSummary;
		this.employeeSumbissionStatus = employeeSumbissionStatus;
		this.managerApprovalStatus = managerApprovalStatus;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.projects = projects;
		this.educations = educations;
		this.skills = skills;
		this.approvedDate = approvedDate;
		this.rejectedDate = rejectedDate;
	}



	public Integer getResumeid() {
		return this.resumeid;
	}

	public void setResumeid(Integer resumeid) {
		this.resumeid = resumeid;
	}

	public EmployeeMaster getEmployeeMaster() {
		return this.employeeMaster;
	}

	public void setEmployeeMaster(EmployeeMaster employeeMaster) {
		this.employeeMaster = employeeMaster;
	}

	
	public String getProfessionalSummary() {
		return this.professionalSummary;
	}

	public void setProfessionalSummary(String professionalSummary) {
		this.professionalSummary = professionalSummary;
	}

	public String getEmployeeSumbissionStatus() {
		return this.employeeSumbissionStatus;
	}

	public void setEmployeeSumbissionStatus(String employeeSumbissionStatus) {
		this.employeeSumbissionStatus = employeeSumbissionStatus;
	}

	public String getManagerApprovalStatus() {
		return this.managerApprovalStatus;
	}

	public void setManagerApprovalStatus(String managerApprovalStatus) {
		this.managerApprovalStatus = managerApprovalStatus;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Set getProjects() {
		return this.projects;
	}

	public void setProjects(Set projects) {
		this.projects = projects;
	}

	public Set getEducations() {
		return this.educations;
	}

	public void setEducations(Set educations) {
		this.educations = educations;
	}

	public Set getSkills() {
		return skills;
	}

	public void setSkills(Set skills) {
		this.skills = skills;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getTotYear() {
		return totYear;
	}

	public void setTotYear(String totYear) {
		this.totYear = totYear;
	}

	public String getTotMon() {
		return totMon;
	}

	public void setTotMon(String totMon) {
		this.totMon = totMon;
	}

	public String getTotalExperience() {
		return totalExperience;
	}

	public void setTotalExperience(String totalExperience) {
		this.totalExperience = totalExperience;
	}

	public String getRelYear() {
		return relYear;
	}

	public void setRelYear(String relYear) {
		this.relYear = relYear;
	}

	public String getRelMon() {
		return relMon;
	}

	public void setRelMon(String relMon) {
		this.relMon = relMon;
	}
	
	public String getRelevantExperience() {
		return relevantExperience;
	}

	public void setRelevantExperience(String relevantExperience) {
		this.relevantExperience = relevantExperience;
	}

	public String getDomain() {
		return domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getCertification() {
		return certification;
	}

	public void setCertification(String certification) {
		this.certification = certification;
	}

}
