package com.qepms.data.sample;

// Generated 5 Dec, 2012 8:47:03 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private int addressid;
	private String address1;
	private String address2;
	private String state;
	private short zip;
	private String createdby;
	private Date createddt;
	private int modifiedby;
	private Date modifieddt;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Address() {
	}

	public Address(int addressid, String address1, String address2,
			String state, short zip, String createdby, Date createddt,
			int modifiedby, Date modifieddt) {
		this.addressid = addressid;
		this.address1 = address1;
		this.address2 = address2;
		this.state = state;
		this.zip = zip;
		this.createdby = createdby;
		this.createddt = createddt;
		this.modifiedby = modifiedby;
		this.modifieddt = modifieddt;
	}

	public Address(int addressid, String address1, String address2,
			String state, short zip, String createdby, Date createddt,
			int modifiedby, Date modifieddt, Set<Employee> employees) {
		this.addressid = addressid;
		this.address1 = address1;
		this.address2 = address2;
		this.state = state;
		this.zip = zip;
		this.createdby = createdby;
		this.createddt = createddt;
		this.modifiedby = modifiedby;
		this.modifieddt = modifieddt;
		this.employees = employees;
	}

	public int getAddressid() {
		return this.addressid;
	}

	public void setAddressid(int addressid) {
		this.addressid = addressid;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public short getZip() {
		return this.zip;
	}

	public void setZip(short zip) {
		this.zip = zip;
	}

	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public Date getCreateddt() {
		return this.createddt;
	}

	public void setCreateddt(Date createddt) {
		this.createddt = createddt;
	}

	public int getModifiedby() {
		return this.modifiedby;
	}

	public void setModifiedby(int modifiedby) {
		this.modifiedby = modifiedby;
	}

	public Date getModifieddt() {
		return this.modifieddt;
	}

	public void setModifieddt(Date modifieddt) {
		this.modifieddt = modifieddt;
	}

	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
