package com.qepms.data.sample;

// Generated 5 Dec, 2012 8:47:03 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9181196794329605703L;
	
	private int deptid;
	private String deptname;
	private String createdby;
	private Date createddt;
	private String modifiedby;
	private Date modifieddt;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Department() {
	}

	public Department(int deptid, String deptname, String createdby,
			Date createddt, String modifiedby, Date modifieddt) {
		this.deptid = deptid;
		this.deptname = deptname;
		this.createdby = createdby;
		this.createddt = createddt;
		this.modifiedby = modifiedby;
		this.modifieddt = modifieddt;
	}

	public Department(int deptid, String deptname, String createdby,
			Date createddt, String modifiedby, Date modifieddt,
			Set<Employee> employees) {
		this.deptid = deptid;
		this.deptname = deptname;
		this.createdby = createdby;
		this.createddt = createddt;
		this.modifiedby = modifiedby;
		this.modifieddt = modifieddt;
		this.employees = employees;
	}

	public int getDeptid() {
		return this.deptid;
	}

	public void setDeptid(int deptid) {
		this.deptid = deptid;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public Date getCreateddt() {
		return this.createddt;
	}

	public void setCreateddt(Date createddt) {
		this.createddt = createddt;
	}

	public String getModifiedby() {
		return this.modifiedby;
	}

	public void setModifiedby(String modifiedby) {
		this.modifiedby = modifiedby;
	}

	public Date getModifieddt() {
		return this.modifieddt;
	}

	public void setModifieddt(Date modifieddt) {
		this.modifieddt = modifieddt;
	}

	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
