package com.qepms.data.sample;

// Generated 5 Dec, 2012 8:47:03 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private int empid;
	private Department department;
	private Address address;
	private String fname;
	private String lname;
	private String createdby;
	private Date createddt;
	private String modifiedby;
	private Date modifieddt;

	public Employee() {
	}

	public Employee(int empid, Department department, Address address,
			String fname, String lname, String createdby, Date createddt,
			String modifiedby, Date modifieddt) {
		this.empid = empid;
		this.department = department;
		this.address = address;
		this.fname = fname;
		this.lname = lname;
		this.createdby = createdby;
		this.createddt = createddt;
		this.modifiedby = modifiedby;
		this.modifieddt = modifieddt;
	}

	public int getEmpid() {
		return this.empid;
	}

	public void setEmpid(int empid) {
		this.empid = empid;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public Date getCreateddt() {
		return this.createddt;
	}

	public void setCreateddt(Date createddt) {
		this.createddt = createddt;
	}

	public String getModifiedby() {
		return this.modifiedby;
	}

	public void setModifiedby(String modifiedby) {
		this.modifiedby = modifiedby;
	}

	public Date getModifieddt() {
		return this.modifieddt;
	}

	public void setModifieddt(Date modifieddt) {
		this.modifieddt = modifieddt;
	}

}
